### PR TITLE
Sj remove archive gating messages

### PR DESCRIPTION
**Pull request by JoblersTune**
All Coil gating messages were removed from the archive post excerpts. The full and partial gating excerpt messages were removed from the customization options as they are no longer displayed anywhere. The maybe_restrict_content function was updated appropriately and an additional the_excerpt filter hook has been added to call a function that filters excerpts in cases where the_content does not.

### CODE REVIEW

**Review by marcperel — COMMENTED** [review]
It looks good to me so far.

We could add a new option called "Excerpt fallback" and then where gated (both partial and fully, we use one option) posts don't have an excerpt, we can display that message, what do you think @SarahCoilAccount?

**Comment by marcperel** [comment]
If I think about it @SarahCoilAccount do we need this filter at all, if we're not actually adding anything extra to the excerpt, then why not just let users have native functionality on their excerpts?

Just a thought. Let me know why we should keep the filters.

**Comment by JoblersTune** [comment]
@marcperel the reason for leaving in the_content filter is that some themes display the full post content on the archive page. If we do not filter the_content then we risk exclusive content being publicly displayed. I don't believe we need the_excerpt filter though. I will remove it.

**Review by marcperel — APPROVED** [review]
Works well, thanks Sarah

**Pull request merged**
