### PR TITLE
Change links to help docs #92

### PR DESCRIPTION
**Pull request by JoblersTune**
The links must have already been updated because they were correct when checked. 

The Configure and use the Coil WordPress plugin link currently opens in the current tab and should rather open in a new tab like the other help links.

The text of this link is slightly confusing and should be changed from "Configure and use the Coil WordPress plugin" to "How to configure and use the Coil WordPress plugin" to make it more clear.

### CODE REVIEW

**Comment by melissahenderson** [comment]
@SarahCoilAccount We set up redirects so that the links wouldn't break.

**Comment by JoblersTune** [comment]
@melissahenderson Thanks for pointing that out, my apologies. I believe this has now been corrected?

**Comment by melissahenderson** [comment]
@SarahCoilAccount I'm not sure. I don't think so. If we take the redirects away those links will break unless they've been updated within the plugin. There's three links in the plugin now.
- Configure and use the Coil WordPress plugin - This should go to https://help.coil.com/docs/monetize/content/wp-overview 
- Learn more about Coil and Web Monetization - This one is fine. It goes to the main help.coil.com site.
- Get a free Coil creator account - This one forwards to https://help.coil.com/docs/monetize/get-creator-account/, but this link will end up changing again when the creator updates are released.

We might need to hold off on closing this until we know what the new link will be for the last item.

**Comment by JoblersTune** [comment]
@melissahenderson I have updated the first link, as you pointed out, to https://help.coil.com/docs/monetize/content/wp-overview.

I see, I didn't realize there were still going to be changes to the Creator account link as well. We will leave the issue open then until the creator updates are released.

**Comment by melissahenderson** [comment]
@SarahCoilAccount I only realized yesterday, after speaking with Fabi, that it would need to change. So this is good timing :)

**Comment by melissahenderson** [comment]
@SarahCoilAccount We received word today that the creator updates are being postponed. The "Get a free Coil creator account" should point to https://help.coil.com/docs/monetize/get-creator-account/. When the creator updates are live, that link might need to be updated again. That's a ways off now, I think.

**Comment by melissahenderson** [comment]
I'm checking with Fabian and Travis about whether the "Get a free Coil creator account" should link to the help doc (https://help.coil.com/docs/monetize/get-creator-account/) or the actual signup page. I'll comment again when I have an answer.

**Comment by melissahenderson** [comment]
@SarahCoilAccount Can we set the "Get a free Coil creator account" link to https://coil.com/creator instead of the help doc?

**Comment by marcperel** [comment]
I've added the correct link now @melissahenderson @SarahCoilAccount thanks

**Review by melissahenderson — APPROVED** [review]

**Review by marcperel — APPROVED** [review]
Great.

**Pull request merged**
